steps:
  - name: goreleaser
    when:
      branch: main
      event: tag
    image: goreleaser/goreleaser
    commands:
      - goreleaser release --clean
    environment:
      GOPRIVATE: github.com/SencilloDev
      GITHUB_TOKEN:
        from_secret: github_token
depends_on:
  - test
